# docker-compose.yml

services:
  db:
    image: postgres:16
    container_name: lumi_pg
    restart: always
    environment:
      - POSTGRES_USER=lumi
      - POSTGRES_PASSWORD=lumi
      - POSTGRES_DB=lumi
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: lumi_api
    restart: always
    ports:
      - '3333:3336'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata: